### ISSUE TITLE
CPU占用高，区域检测有时会卡住

### ISSUE THREAD

**Issue by cuiliang** [HandyOrg/HandyScreenshot#3]
即便在没有截图的时候也会有较高CPU占用。
有时候区域检测会停在某个位置不再跟随鼠标位置更新。

![image](https://user-images.githubusercontent.com/1972649/101278665-fd3cc480-37f7-11eb-83ef-1da237b07eb9.png)

**Comment by cuiliang** [comment]
![image](https://user-images.githubusercontent.com/1972649/101278706-53116c80-37f8-11eb-8b7a-d371de7d861f.png)

**Comment by DingpingZhang** [comment]
> 有时候区域检测会停在某个位置不再跟随鼠标位置更新。

当出现描述中情况时，请查看右上角信息栏里的 `Mode` 字段是否为 `AutoDetect`（此时很可能是 `Fixed`）。

![image](https://user-images.githubusercontent.com/8541016/101748849-0683a500-3b08-11eb-91a4-bfaa339a0823.png)

> 即便在没有截图的时候也会有较高CPU占用。

从你的截图里，看起来 CPU 占用并不是很高呀？

**Comment by cuiliang** [comment]
嗯，还可以了，可能时以为一直在检测控件。
