### ISSUE TITLE
项目定位建议

### ISSUE THREAD

**Issue by cuiliang** [HandyOrg/HandyScreenshot#4]
目前有很多截图工具，但是好像没有一个公共可用的截图功能的库，我还花了一些时间找商业版的，也没有找到。

如果有兴趣，可以做一个这样的库，主要可以提供这样的功能：
- 选择区域截图，返回：位图对象、截图区域坐标；（主要功能）
- 选取颜色：返回颜色值和取点坐标；
- 整屏截图、指定位置截图，返回位图对象；
- 选择区域范围，返回区域坐标；

大佬加油~

**Comment by DingpingZhang** [comment]
> 选择区域截图，返回：位图对象、截图区域坐标；

这个 API 不是很理解：为什么要返回截图区域坐标呢？这个坐标应该是传入的吧？

```
(Rect) --> Image

Rect { x, y, width, height }
```

你可以看一下当前项目中的 `HandyScreenshot.Helpers.ScreenshotHelper.CaptureScreen(ReadOnlyRect rect): BitmapSource` 是不是你想要的？

**Comment by cuiliang** [comment]
区域用于解决选择屏幕范围的情况。比如先选择了一个范围，然后每隔几秒从这个区域自动截图一次...

**Comment by cuiliang** [comment]
Winform 自己写了一个，基本满足需求了😂
